import { generatePlaywrightSpec } from '../generator/playwright-spec-generator.js';
import { CodexAgentAdapter, promptPath } from './codex-agent-adapter.js';

export class GeneratorAgent {
  constructor({ name = 'Agent Generator', codex = new CodexAgentAdapter() } = {}) {
    this.name = name;
    this.codex = codex;
  }

  async generate({ recording, reviewFeedback = [], runtimeFeedback = null }) {
    const result = await this.codex.run({
      promptPath: promptPath('generator-agent.md'),
      payload: { recording, reviewFeedback, runtimeFeedback },
      fallback: () => generatePlaywrightSpec(recording, reviewFeedback)
    });

    if (result?.mode === 'codex') {
      return {
        targetPath: 'tests/generated-checkout.spec.ts',
        code: result.output,
        agent: this.name,
        mode: 'codex',
        notes: ['Generated by Codex adapter from recorder action log.']
      };
    }

    return {
      ...result,
      agent: this.name,
      mode: 'deterministic-fallback',
      notes: [
        'Generated from recorder action log.',
        'Locator priority is data-testid > role/text > css > xpath.',
        runtimeFeedback ? `Runtime feedback included: ${runtimeFeedback.summary}` : null
      ].filter(Boolean)
    };
  }
}
